; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = secrets.ini

[device]
name = hatch

[env:nodemcu-32s]
platform = espressif32@6.4.0
board = m5stack-atom
framework = arduino
extra_scripts = pre:../libcommon/version_flag.py
lib_deps =
	file://../libcommon
	h2zero/NimBLE-Arduino@^1.4.1
build_flags =
  	-DENABLE_WIFI
    -DENABLE_REMOTE_LOG
	-DENABLE_MQTT
	-DENABLE_MQTT_V2
	-DMQTT_NAMESPACE=nursery
	-DENABLE_PULL_OTA
	-DDEVICE_NAME=${device.name}
	-DMQTT_ID=HatchController
	-DMQTT_USERNAME=${mqtt.username}
	-DMQTT_PASSWORD=${mqtt.password}
